### ISSUE TITLE
Some errors in stage of building container occurs

### ISSUE THREAD

**Issue by RodionKorneev** [nikitasavinov/checkstyle-action#35]
Everything worked well until today. Could you help to fix the problem, please?

Debug mode log of **Build nikitasavinov/checkstyle-action@0.6.0** step:
```text
##[debug]Evaluating condition for step: 'Build nikitasavinov/checkstyle-action@0.6.0'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build nikitasavinov/checkstyle-action@0.6.0
- Build container for action use: '/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0/Dockerfile'.
Error: Docker build failed with exit code 1
##[debug]System.InvalidOperationException: Docker build failed with exit code 1
##[debug]   at GitHub.Runner.Worker.ActionManager.BuildActionContainerAsync(IExecutionContext executionContext, Object data)
##[debug]   at GitHub.Runner.Worker.JobExtensionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: Build nikitasavinov/checkstyle-action@0.6.0
```

Unwrapped build details:
```text
Build container for action use: '/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0/Dockerfile'.
  /usr/bin/docker build -t 49859c:376a00c8f37445c893f0c3dd0e5a25dd -f "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0/Dockerfile" "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0"
  Sending build context to Docker daemon  13.31kB
  
  Step 1/6 : FROM openjdk:17-alpine
  17-alpine: Pulling from library/openjdk
  5843afab3874: Pulling fs layer
  53c9466125e4: Pulling fs layer
  d8d715783b80: Pulling fs layer
  53c9466125e4: Verifying Checksum
  53c9466125e4: Download complete
  5843afab3874: Verifying Checksum
  5843afab3874: Download complete
  5843afab3874: Pull complete
  53c9466125e4: Pull complete
  d8d715783b80: Verifying Checksum
  d8d715783b80: Download complete
  d8d715783b80: Pull complete
  Digest: ...
  Status: Downloaded newer image for openjdk:17-alpine
   ---> 264c9bdce361
  Step 2/6 : ENV REVIEWDOG_VERSION=v0.14.0
   ---> Running in e9f4762f42f0
  Removing intermediate container e9f4762f42f0
   ---> 308680e0a4de
  Step 3/6 : RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}
   ---> Running in 5e[28](<MY_JOB_URL>#step:2:28)94034192
  reviewdog/reviewdog info checking GitHub for tag 'v0.14.0'
  reviewdog/reviewdog info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/Linux/x86_64
  wget: server returned error: HTTP/1.1 400 Bad Request
  The command '/bin/sh -c wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 7.217 seconds before retry.
  /usr/bin/docker build -t 49859c:376a00c8f37445c893f0c3dd0e5a25dd -f "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0/Dockerfile" "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0"
  Sending build context to Docker daemon  13.31kB
  
  Step 1/6 : FROM openjdk:17-alpine
   ---> 264c9bdce361
  Step 2/6 : ENV REVIEWDOG_VERSION=v0.14.0
   ---> Using cache
   ---> [30](<MY_JOB_URL>#step:2:30)8680e0a4de
  Step 3/6 : RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}
   ---> Running in f751b4490df8
  reviewdog/reviewdog info checking GitHub for tag 'v0.14.0'
  reviewdog/reviewdog info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/Linux/x86_64
  wget: server returned error: HTTP/1.1 400 Bad Request
  The command '/bin/sh -c wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 1.894 seconds before retry.
  /usr/bin/docker build -t 49859c:376a00c8f37445c893f0c3dd0e5a25dd -f "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0/Dockerfile" "/home/runner/work/_actions/nikitasavinov/checkstyle-action/0.6.0"
  Sending build context to Docker daemon  13.[31](<MY_JOB_URL>#step:2:31)kB
  
  Step 1/6 : FROM openjdk:17-alpine
   ---> 264c9bdce361
  Step 2/6 : ENV REVIEWDOG_VERSION=v0.14.0
   ---> Using cache
   ---> 308680e0a4de
  Step 3/6 : RUN wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}
   ---> Running in 537fd4f[34](<MY_JOB_URL>#step:2:34)efc
  reviewdog/reviewdog info checking GitHub for tag 'v0.14.0'
  reviewdog/reviewdog info found version:  <!DOCTYPE html> <html lang= for  <!DOCTYPE html> <html lang=/Linux/x86_64
  wget: server returned error: HTTP/1.1 [40](<MY_JOB_URL>#step:2:40)0 Bad Request
  The command '/bin/sh -c wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin/ ${REVIEWDOG_VERSION}' returned a non-zero code: 1
```

**Comment by RodionKorneev** [comment]
At the moment the problem is solved
